### ISSUE TITLE
Конфигурирование раскладки (layout) через json

### ISSUE THREAD

**Issue by nixel2007** [autumn-library/autumn-logos#1]
Указать имя класса, которое устанавливаться методом Лог.УстановитьРаскладку

Не знаю, нужно ли делать их синглтонами (как аппендеры) или инстанцировать на каждый лог отдельно.

**Comment by Nivanchenko** [comment]
А как ты видишь, что должно быть в json? 
что-то типо ?
```json
{
    "logos": {
      "logger": { 
        "my.logger.WARN": {"level":"WARN", "layout": "simple"}
       }
    }
     "layouts": { 
        "simple": "%Уровень% - %ИмяЛога% - %Сообщение%"   
     }
  }
```

**Comment by Nivanchenko** [comment]
Или просто
```json
{
    "logos": {
      "logger": { 
        "my.logger.WARN": {"level":"WARN", "layout": "ИмяКлассаКотороеВЗаготовкеПроинстанцируетсяЧерезНовый"}
       }
    }
  }
```

**Comment by nixel2007** [comment]
> Или просто
> ```json
> {
>     "logos": {
>       "logger": { 
>         "my.logger.WARN": {"level":"WARN", "layout": "ИмяКлассаКотороеВЗаготовкеПроинстанцируетсяЧерезНовый"}
>        }
>     }
>   }
> ```


Вот так, да. Хотя менять стандартную через шаблонную строку - отличная идея. Можно сделать и так и так :)

**Comment by nixel2007** [comment]
Для овм мне нужен класс. Причём желудь, так как я к нему потом обращаюсь. Хотя если из лога можно получить аппендер, то это не так критично.

**Comment by nixel2007** [comment]
Реализовано в 1.1.0
